version: "3.8"

services:
  microcurriculo:
    image: microcurriculo:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
      - DATABASE_URL=jdbc:postgresql://microcurriculo-db:5432/microcurriculo
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=komodor11
      - CLIENTID=177239891830-qjkhdrr3i2gocf399hn4atvh9k27jos8.apps.googleusercontent.com
      - CLIENTSECRET=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
      - KEYSECRET_SECURITY=eyTJhbGcdiOiJIUzUxMiIsInR5cCI6IkpaXVCJ9.eyJzdWIiOiIxMjM0NTY3sdODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA
      - EXPIRE_DAYS_SECURITY=21600000
      - EMAIL_USERNAME=edu.ufps10@gmail.com
      - EMAIL_PASSWORD=mvui ehyh jdgl wmgb
    depends_on:
      - microcurriculo-db
    volumes:
      - microcurriculo-data:/var/lib/postgresql/data

  microcurriculo-db:
    container_name: microcurriculo-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: microcurriculo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: komodor11
    volumes:
      - microcurriculo-data:/var/lib/postgresql/data

volumes:
  microcurriculo-data:
