package com.micro.demo.entities.enums;

public enum ElectivaProfesional {
    TEORIA_DE_GRAFOS("1150710", "TEORIA DE GRAFOS"),
    GERENCIA_Y_TECNOLOGIA("1150712", "GERENCIA Y TECNOLOGIA"),
    INTELIGENCIA_ARTIFICIAL("1150715", "INTELIGENCIA ARTIFICIAL"),
    MICROPROCESADORES("1150716", "MICROPROCESADORES"),
    TECNICAS_GERENCIALES_NEGOCIACION("1150718", "TECNICAS GERENCIALES DE NEGOCIACION"),
    RECUPERACION_INFORMACION("1150811", "RECUPERACION DE LA INFORMACION"),
    CONTRATACION_PROYECTOS_SISTEMAS("1150813", "CONTRATACION DE PROYECTOS DE SISTEMAS"),
    ROBOTICA("1150814", "ROBOTICA"),
    TRATAMIENTO_IMAGENES("1150815", "TRATAMIENTO DE IMÁGENES"),
    GESTION_BASES_DATOS("1150817", "GESTION DE BASES DE DATOS"),
    INFORMATICA_EDUCATIVA("1150911", "INFORMATICA EDUCATIVA"),
    SISTEMAS_INFORMACION("1150912", "SISTEMAS DE INFORMACION"),
    REDES_CONVERGENTES("1150913", "REDES CONVERGENTES"),
    REDES_INALAMBRICAS("1150914", "REDES INALAMBRICAS"),
    DESARROLLO_APLICACIONES_WEB("1150924", "DESARROLLO DE APLICACIONES WEB"),
    INGENIERIA_ONTOLOGICA("1151010", "INGENIERÍA ONTOLOGICA"),
    ADMIMISTRACION_SO_RED("1151011", "ADMIMISTRACION DE SO DE RED"),
    DATAWAREHOUSING("1151012", "DATAWAREHOUSING"),
    AUDITORIA_SISTEMAS("1151013", "AUDITORIA DE SISTEMAS"),
    DESARROLLO_APLICACIONES_MOVILES("1151014", "DESARROLLO DE APLICACIONES MOVILES"),
    SEGURIDAD_INFORMATICA("1151016", "SEGURIDAD INFORMATICA"),
    ARQUITECTURA_ORIENTADA_SERVICIOS("1151017", "ARQUITECTURA ORIENTADA A SERVICIOS");

    private final String codigo;
    private final String nombre;

    ElectivaProfesional(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public String getCodigo() {
        return codigo;
    }

    public String getNombre() {
        return nombre;
    }
}
