package com.micro.demo.entities.enums;


public enum AsignaturaObligatoria {
    CALCULO_DIFFERENCIAL("1155101", "CALCULO DIFERENCIAL"),
    MATEMATICAS_DISCRETAS("1155102", "MATEMATICAS DISCRETAS"),
    FUNDAMENTOS_PROGRAMACION("1155104", "FUNDAMENTOS DE PROGRAMACION"),
    INTRO_INGENIERIA_SISTEMAS("1155105", "INTRO A INGENIERIA DE SISTEMAS"),
    COMUNICACION_I("1155106", "COMUNICACION I"),
    INTROD_VIDA_UNIVERSITARIA("1155108", "INTROD. A LA VIDA UNIVERSITARIA"),
    CALCULO_INTEGRAL("1155201", "CALCULO INTEGRAL"),
    ALGEBRA_LINEAL("1155202", "ALGEBRA LINEAL"),
    FISICA_MECANICA("1155203", "FISICA MECANICA"),
    PROGR_ORIENTADA_OBJETOS_I("1155204", "PROGR ORIENTADA A OBJETOS I"),
    COMUNICACION_II("1155206", "COMUNICACION II"),
    SEMINARIO_INTEGRADOR_I("1155109", "SEMINARIO INTEGRADOR I"),
    CALCULO_VECTORIAL("1155301", "CALCULO VECTORIAL"),
    FISICA_ELECTROMAGNETICA("1155303", "FISICA ELECTROMAGNETICA"),
    ESTRUCTURA_DATOS("1155304", "ESTRUCTURA DE DATOS"),
    PROGR_ORIENTADA_OBJETOS_II("1155305", "PROGR ORIENTADA A OBJETOS II"),
    SEMINARIO_INVESTIGACION_I("1155306", "SEMINARIO DE INVESTIGACION I"),
    ECUACIONES_DIFERENCIALES("1155401", "ECUACIONES DIFERENCIALES"),
    PROBABILIDAD_ESTADISTICA("1155402", "PROBABILIDAD Y ESTADISTICA"),
    ONDAS_PARTICULAS("1155403", "ONDAS Y PARTICULAS"),
    ANALISIS_ALGORITMOS("1155404", "ANALISIS DE ALGORITMOS"),
    TEORIA_COMPUTACION("1155305", "TEORIA DE LA COMPUTACION"),
    ANALISIS_NUMERICO("1155501", "ANALISIS NUMERICO"),
    INVESTIGACION_OPERACIONES("1155502", "INVESTIGACIÓN DE OPERACIONES"),
    ELECTRONICA("1155503", "ELECTRONICA"),
    ARQUITECTURA_COMPUTADORES("1155504", "ARQUITECTURA DE COMPUTADORES"),
    SEMINARIO_INVESTIGACION_II("1155506", "SEMINARIO DE INVESTIGACIÓN II"),
    SISTEMAS_OPERATIVOS("1155604", "SISTEMAS OPERATIVOS"),
    BASES_DATOS("1155605", "BASES DE DATOS"),
    PROGRAMACION_WEB("1155606", "PROGRAMACION WEB"),
    CONSTITUCION_CIVISMO("1155607", "CONSTITUCION Y CIVISMO"),
    PLANEACION_ESTRATEGICA_SI("1155608", "PLANEACION ESTRATEGICA DE SI"),
    SEMINARIO_INTEGRADOR_II("1155609", "SEMINARIO INTEGRADOR II"),
    TEORIA_GENERAL_COMUNICACIONES("1155704", "TEORÍA GENERAL DE LAS COMUNICACIONES"),
    ANALISIS_DISEÑO_SISTEMAS("1155705", "ANÁLISIS Y DISEÑO DE SISTEMAS"),
    SEMINARIO_INVESTIGACION_III("1155706", "SEMINARIO DE INVESTIGACION III"),
    ETICA_PROFESIONAL("1155707", "ETICA PROFESIONAL"),
    ADMINISTACION_PROYECTOS_INFORMATICOS("1155708", "ADMINISTACION DE PROYECTOS INFORMATICOS"),
    REDES_COMPUTADORES("1155804", "REDES DE COMPUTADORES"),
    INGENIERIA_SOFTWARE("1155805", "INGENIERÍA DE SOFTWARE"),
    FORMULACION_EVALUACION_PROYECTOS("1155808", "FORMULACION Y EVALUACION DE PROYECTOS DE SISTEMAS"),
    SEMINARIO_INTEGRADOR_III("1155809", "SEMINARIO INTEGRADOR III"),
    GESTION_TIC("1155908", "GESTION DE TIC"),
    PRACTICA_SISTEMAS("1155909", "PRACTICA EN SISTEMAS"),
    ARQUITECTURA_SOFTWARE("1155806", "ARQUITECTURA DE SOFTWARE"),
    PROYECTO_GRADO("1156009", "PROYECTO DE GRADO");

    private final String codigo;
    private final String nombre;

    AsignaturaObligatoria(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public String getCodigo() {
        return codigo;
    }

    public String getNombre() {
        return nombre;
    }
}

